/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Usuário
 */
public class Menu extends javax.swing.JFrame {
    private String usuarioAutenticado;
    
    public String getusuarioAutenticado(){
        return usuarioAutenticado;
    }
    /**
     * Creates new form Menu
     */
    public Menu() {
        Autenticacao login = new Autenticacao(null,true);
        login.setVisible(true);
        usuarioAutenticado = login.getUsuarioAutenticado();
        if(!usuarioAutenticado.equals("")){
        initComponents();
        lblUsuarioAutenticado.setText("Usuário: " + usuarioAutenticado);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuBasicos = new javax.swing.JMenu();
        jMenuItemCategCliente = new javax.swing.JMenuItem();
        jMenuItemCategProduto = new javax.swing.JMenuItem();
        jMenuItemClientesPopup = new javax.swing.JMenuItem();
        jMenuItemProdutosPopup = new javax.swing.JMenuItem();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblUsuarioAutenticado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemTrocarSenha = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemCategoriaClientes = new javax.swing.JMenuItem();
        jMenuItemCategoriaProdutos = new javax.swing.JMenuItem();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemProdutos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemAjuda = new javax.swing.JMenuItem();
        jMenuItemVersao = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuCadastros.setText("Cadastros");

        jMenuBasicos.setText("Basicos");

        jMenuItemCategCliente.setText("Cliente");
        jMenuBasicos.add(jMenuItemCategCliente);

        jMenuItemCategProduto.setText("Produto");
        jMenuItemCategProduto.setToolTipText("");
        jMenuBasicos.add(jMenuItemCategProduto);

        jMenuCadastros.add(jMenuBasicos);

        jMenuItemClientesPopup.setText("ClientesPopup");
        jMenuCadastros.add(jMenuItemClientesPopup);

        jMenuItemProdutosPopup.setText("ProdutosPopup");
        jMenuItemProdutosPopup.setToolTipText("");
        jMenuCadastros.add(jMenuItemProdutosPopup);

        jPopupMenu1.add(jMenuCadastros);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplo MDI e SDI");
        setExtendedState(6);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.add(filler1);

        lblUsuarioAutenticado.setText("Usuário:");
        jToolBar2.add(lblUsuarioAutenticado);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pessoa-nao-autorizada.png"))); // NOI18N
        jButton1.setText("Alterar Senha");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTrocarSenhaActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);
        jToolBar2.add(filler2);

        jMenu1.setText("Arquivo");

        jMenuItemTrocarSenha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemTrocarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pessoa-nao-autorizada.png"))); // NOI18N
        jMenuItemTrocarSenha.setText("Trocar Senha");
        jMenuItemTrocarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTrocarSenhaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTrocarSenha);
        jMenu1.add(jSeparator1);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastros");

        jMenu3.setText("Básicos");

        jMenuItemCategoriaClientes.setText("Categoria de Clientes");
        jMenuItemCategoriaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoriaClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCategoriaClientes);

        jMenuItemCategoriaProdutos.setText("Categoria de Produtos");
        jMenuItemCategoriaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoriaProdutosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCategoriaProdutos);

        jMenu2.add(jMenu3);

        jMenuItemClientes.setText("Clientes");
        jMenu2.add(jMenuItemClientes);

        jMenuItemProdutos.setText("Produtos");
        jMenu2.add(jMenuItemProdutos);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Sobre");

        jMenuItemAjuda.setText("Ajuda");
        jMenuItemAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjudaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAjuda);

        jMenuItemVersao.setText("Versao");
        jMenuItemVersao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVersaoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemVersao);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Exercícios");

        jMenu6.setText("Exercícios");

        jMenuItem1.setText("AC2");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenu5.add(jMenu6);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2)
                .addContainerGap())
            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        WindowEvent winEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winEvent);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAjudaActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if(evt.isPopupTrigger()){
            jPopupMenu1.show(this,evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_formMouseReleased

    private void jMenuItemTrocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTrocarSenhaActionPerformed
        TrocarSenha tela = new TrocarSenha();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemTrocarSenhaActionPerformed

    private void jMenuItemVersaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVersaoActionPerformed
        Versao tela = new Versao(this,true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemVersaoActionPerformed

    private void jMenuItemCategoriaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoriaClientesActionPerformed
        CategoriaClientes tela = CategoriaClientes.getInstance();
        tela.pack();
        if(!tela.isVisible()){
            jDesktopPane2.add(tela);
            tela.setVisible(true);
        }else
            tela.moveToFront();
        
    }//GEN-LAST:event_jMenuItemCategoriaClientesActionPerformed

    private void jMenuItemCategoriaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoriaProdutosActionPerformed
        CategoriaProdutos tela = CategoriaProdutos.getInstance();
        tela.pack();
        if(!tela.isVisible()){
            jDesktopPane2.add(tela);
            tela.setVisible(true);
        }else
            tela.moveToFront();
    }//GEN-LAST:event_jMenuItemCategoriaProdutosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(JOptionPane.showConfirmDialog(this, "Deseja realmente sair?","Atenção",JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION){
            setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        }else{
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Exercicio1 tela = Exercicio1.getInstance();
        tela.pack();
        if(!tela.isVisible()){
            jDesktopPane2.add(tela);
            tela.setVisible(true);
        }else
            tela.moveToFront();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBasicos;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAjuda;
    private javax.swing.JMenuItem jMenuItemCategCliente;
    private javax.swing.JMenuItem jMenuItemCategProduto;
    private javax.swing.JMenuItem jMenuItemCategoriaClientes;
    private javax.swing.JMenuItem jMenuItemCategoriaProdutos;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemClientesPopup;
    private javax.swing.JMenuItem jMenuItemProdutos;
    private javax.swing.JMenuItem jMenuItemProdutosPopup;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTrocarSenha;
    private javax.swing.JMenuItem jMenuItemVersao;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblUsuarioAutenticado;
    // End of variables declaration//GEN-END:variables
}
